name: boolean_nca_cc_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9 # JAX and Jraph typically require a recent Python
  - matplotlib
  - pillow
  - tqdm
  - jraph
  - numpy
  - jax # Includes jaxlib by default from conda-forge
  - optax
  - flax
  - imgui-bundle # For fixed_random_wires_demo.py
  - pip
  - pip:
    - notebook # For running the .ipynb file
    - ipython # For interactivity, often used with imgui-bundle 