# @package _global_
# 6-bit binary multiplication task (smaller for faster experiments)

task:
  name: "binary_multiply"
  description: "6-bit binary multiplication"
  
  # Problem dimensions
  input_n: 6
  output_n: 6
  
  # Circuit architecture
  arity: 4
  layer_n: 2
  width_factor: 2
  
  # Train/test split
  test_ratio: 0.25
