_target_: boolean_nca_cc.models.CircuitGNN
# Configuration for Graph Neural Network model

type: "gnn"
mlp_dim: null # If null, will be set to circuit_hidden_dim * 2
message_passing: true
use_attention: false 
mlp_n_layers: 1
