_target_: boolean_nca_cc.models.CircuitSelfAttention
# Configuration for Self-Attention model

type: "self_attention"
circuit_hidden_dim: 16  # Added from base
attention_dim: 256
mlp_dim: null # If null, will be set to attention_dim * mlp_dim_multiplier
mlp_dim_multiplier: 4
num_heads: 8
num_layers: 1
dropout_rate: 0.0 