_target_: boolean_nca_cc.models.CircuitSelfAttention
# Configuration for Self-Attention model

defaults:
  - _base

type: "self_attention"
attention_dim: 128
mlp_dim: null # If null, will be set to attention_dim * mlp_dim_multiplier
mlp_dim_multiplier: 2
num_heads: 8
num_layers: 1
dropout_rate: 0.0 