hpc:
  default_resources: "select=1:ncpus=4:ngpus=1:mem=64gb"
  default_walltime: "72:00:00"
  max_array_size: 10000
  system: pbs
metadata:
  created_at: '2025-06-18T16:22:03.838675'
  created_by: HSM (HPC Sweep Manager)
  version: 1.0.0
paths:
  config_dir: /rds/general/user/gb21/home/PhD/ANN/NCA/boolean_nca_cc/configs
  output_dir: outputs
  python_interpreter: /rds/general/user/gb21/home/anaconda3/envs/cc_nca/bin/python
  train_script: /rds/general/user/gb21/home/PhD/ANN/NCA/boolean_nca_cc/train.py
project:
  name: boolean_nca_cc
  root: /rds/general/user/gb21/home/PhD/ANN/NCA/boolean_nca_cc
wandb:
  entity: ''
  project: boolean_nca_cc
