# Main configuration file for single experiment training
defaults:
  - task: binary_add_8bit
  - optimizer: adam_default
  - sparsity: none
  - wandb: enabled
  - cross_validation: kfold
  - _self_

# Training configuration
training:
  num_steps: 128
  loss_type: "l4"

# Circuit generation seed
circuit_seed: 123

# Train / Test base seed
train_test_base_seed: 42

# Default WandB configuration (can be overridden by wandb configs)

# Hydra logging
hydra:
  run:
    dir: outputs/bp_sweep/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: bp_sweep
